name: Raspberry Pi Build
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.RPIHOST }}
          username: ${{ secrets.RPIUSERNAME }}
          password: ${{ secrets.RPIPASSWORD }}
          port: ${{ secrets.RPIPORT }}
          script:
            rm -rf /tmp/{{ github.event.repository.name }}_build
            mkdir /tmp/{{ github.event.repository.name }}_build
            cd /tmp/{{ github.event.repository.name }}_build
            git clone ${{ github.event.repository.clone_url }}
            cd ${{ github.event.repository.name }} && cmake -B build && cmake --build build
            if [ $? -ne 0 ]; then exit 1; fi
            rm -rf /tmp/{{ github.event.repository.name }}_build
            echo "Build successful!"