name: Raspberry Pi Build

on: [push, pull_request]
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    name: Build
    if: "!contains(github.event.commits[0].message, '[skip rpi-build]')"
    runs-on: ubuntu-latest

    steps:
      - name: Build
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.RPIHOST }}
          username: ${{ secrets.RPIUSERNAME }}
          password: ${{ secrets.RPIPASSWORD }}
          port: ${{ secrets.RPIPORT }}

          script: |
            export BUILD_DIR=/tmp/${{ github.event.repository.name }}_build_commit_${{ github.sha }}
            rm -rf $BUILD_DIR
            mkdir $BUILD_DIR
            cd $BUILD_DIR
            if [ -n "${{ github.event.pull_request.head.sha }}" ]; then
              git clone --depth 1 --single-branch --branch ${{ github.event.pull_request.head.ref }} ${{ github.event.repository.clone_url }} ${{ github.event.repository.name }}
              echo "Building pull request ${{ github.event.pull_request.number }} from branch ${{ github.ref_name }}"
            else
              git clone --depth 1 --single-branch --branch ${{ github.ref_name }} ${{ github.event.repository.clone_url }} ${{ github.event.repository.name }}
              echo "Building branch ${{ github.ref_name }}"
            fi
            cd ${{ github.event.repository.name }} && cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
            cmake --build build --config ${{env.BUILD_TYPE}}
            if [ $? -ne 0 ]; then exit 1; fi
            rm -rf $BUILD_DIR
            echo "Build successful"
